### ISSUE TITLE
请问这个efi能驱动同配置，显卡是rx580吗

### ISSUE THREAD

**Issue by wyl2607** [Leif160519/Gigabyte-B85-HD3-EFI#1]
想知道如果能驱动580，系统还能升级吗？

**Comment by Leif160519** [comment]
> 想知道如果能驱动580，系统还能升级吗？

目前这个EFI的适用范围仅限于10.13.6，高版本没有试过，因为该配置的电脑我已经拆散了，故不更新了，抱歉
